### ISSUE TITLE
withLayout

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/Porten-onix-homework#20]
Нельзя использовать HOC в рендере компонента, Это плохо влияет на производительность 
```
const HomePageComponent = withLayout(HomePage);
const ListPageComponent = withLayout(ListPage);
```
Функциональная компонента по сути вся является рендером
https://ru.reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method

**Comment by YourContender** [comment]
исправил )
