### ISSUE TITLE
Layout child

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/Porten-onix-homework#6]
1. ` const child = children;` не вижу смысла в таком переименовании, но если очень хочется то можно через распаковку `function Layout({ children: child }) {`
2. PropTypes для `children`  лучше всего обычно использовать PropTypes.node - тогда будет подходить и строка и реакт элемент и массив реактовских элементов
3. defaultProps `children: <Header />, ` - не уверен чем обосновать, но мне не нравится, обычно записываю как-то так
```
<main>
    {child || (<Header />)}
</main>
...
Layout.defaultProps = { 
  children: null, 
};
```

**Comment by YourContender** [comment]
исправил
