### ISSUE TITLE
Нельзя привязывать логику в внешнему виду

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/Porten-onix-homework#7]
`CardWatch.js` 
```
  onActiveItem = (e, id) => {
    const { onActiveCard } = this.props;
    return e.target.textContent !== 'Удалить' && onActiveCard(id);
  };
```
То как это отработает зависит от текста. А если появится мультиязычность? А еще интереснее если в хроме нажать ПКМ в перевести сайт на другой язык. 
Добавь для кнопки атрибут name и проверяй уже его

**Comment by YourContender** [comment]
исправил )
