### ISSUE TITLE
onClick={() => cancelFilterMethod()}

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [YourContender/Porten-onix-homework#8]
```
 <Dropdown.Item key={country.length + 1} onClick={() => cancelFilterMethod()}>сброс</Dropdown.Item>
```
Не нужно без необходимости создавать ненужные функции. Например в твоем случае при каждом перерендере твоего компонента так же будет перерендериться и `Dropdown.Item` как бы он не был оптимизирован. Потому что при каждом перерендере создается новая функция `() => cancelFilterMethod()` а избежать этого очень просто 
```
 <Dropdown.Item key={country.length + 1} onClick={cancelFilterMethod}>сброс</Dropdown.Item>
```

**Comment by YourContender** [comment]
исправил
